# Override these attribute values in this environment specific configuration.

[application]
google_project_id = ""
google_api_key = ""
signer_service_account_email = ""

[storage]
high_res_input_bucket = ""
low_res_output_bucket = ""
